### ISSUE TITLE
Snapshot restores cause DB issues

### ISSUE THREAD

**Issue by twforeman** [prometheus/tsdb#446] opened 2018-11-06 15:34 UTC
Re: https://github.com/prometheus/prometheus/issues/4643

Running version 2.4.3.

After taking a snapshot and copying it to S3 then restoring it to a new disk volume and pointing prometheus to it after about four hours we start seeing compaction errors complaining about time over lap issues.

This was supposedly fixed in 2.3.1 but appears to still be broken.

I'm going to break my test prometheus installation so I can gather some logs and attach them here, but it will be about four hours.

Here is a theory about why it's not working, but I have no idea whether it's reasonable:

Taking a snapshot makes hard links to the DB files, not copies. Is it possible that the issue is caused because there is a time lag between when the snapshot is created and when the files are copied elsewhere and some of the files that are hard linked are still getting updated?

**Comment by codesome** [comment] 2018-11-06 17:08
I suspect this is something to do with the head block (not sure, will know from logs), and that the head block of the snapshot and the new head block overlap. Did you have the head in your snapshot? (`skip_head=false`).

**Comment by twforeman** [comment] 2018-11-06 18:18
`level=info ts=2018-11-06T18:16:23.804510458Z caller=compact.go:398 component=tsdb msg="write block" mint=1541512800000 maxt=1541520000000 ulid=01CVN3R6Y2BVRX3FTM1NSTZ0WG
level=error ts=2018-11-06T18:16:35.898970177Z caller=db.go:305 component=tsdb msg="compaction failed" err="reload blocks: invalid block sequence: block time ranges overlap: [mint: 1541512800000, maxt: 1541512897799, range: 1m37s, blocks: 59]: <ulid: 01CVMN89AC8XWPAB8M99RNA9D4, mint: 1541512302989, maxt: 1541512897799, range: 9m54s>, <ulid: 01CVMZPZQ0SRA3PVNGMSMH1NEK, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZJEBQD57VKNQT32X2FDCV, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZK0W09KMF5J0JP1R1YJC9, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZKMQH4DWAFQT9WBXN7WXE, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZMDY47YKY2ZC4E8Z7ZG94, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZNFTWGQ2M8T3FMPHFQJET, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZHW8QARZ4RTWZ8GCX39SN, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZSBMXSPX2Y7JVAYT64HHR, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZVQXB0H7FC7B7MGT7P837, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVMZY5QKHN6BZW4SD5ZW9S7G, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN00KY24RS7W0VB68TDBTDA, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0303A05GAYNKVAG3W7EK2, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN05E4B3K3B866EQW92YX8Q, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN07W92QMDJ6JWYH65D3Q5R, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0A9D5NA0V6ZSK45G1W2SC, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0CPZZP1TMEJX08NRNZ2F3, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0F6PRRMXMYQZD5VEYTEWV, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0HM394AQSN474169KQC2M, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0M2VZS7NMVKBGPBGMSS3C, mint
: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0PHE98BNBKVZN4SCADAC1, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0RYJ5SW7T2ZGSQEZFV8ME, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0VE2W5KB3J01F5BW185ZN, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN0XWTAS9WWW2PGAR4GXY8H, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN10AZZABJ3D7M663MMKTHG, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN12V0773WE4X8NBGZN38FH, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN15B4CX8XVB5CCBFEZ3H57, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN17V7ZN8X2VYEPQBSV6FTD, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1AAGPGS5ACJH8QW2GMSEH, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1CTZZGPHDE9QQ79ZY7D5A, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1FBQAJEZAPKEY0NVP3MCE, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1HW5YHYXMMVWNS42TJQDG, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1MC3A2HAT1DRKXYWEJ5DY, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1PWRQX2JHNMVZTC9WMABB, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1SFW00NW3VJHF2TQKC0X3, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1W22PGXH4S8RFETNP0FQE, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN1YKPC8BW7X899NFD1WSHM, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN216MSGCNA71Z4S1S17JTK, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN23R4YN678J0KZ4YMSBPH4, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN26B545G9HRGNXWZ6W8T4J, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN28XEDKTY9EW5TPB26BWN4, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2BERFWAXSBVDFM1J9QYCB, mint: 
1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2DZDPJ6BD7BPZG7714TR3, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2GHYWJJ5KC53FVSS02H44, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2K5C5KCD8BS5XVGXZCSDQ, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2NRMAVH8FBWZ5ESKPPVVZ, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2RCAXKEV139X3EFV3MM5P, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2TZPVTREZRWS4CDQ2MZ27, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN2XKW6E5MPAJX45DMVGXTE, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3079DTN2F8RXHXEHS8TBP, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN32VRJNBQ3NNQ46P15MMX4, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN35G8FEP2JWH47RHFMGJ8F, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN38527P76Y9E112NGZPJQB, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3ATWT61S2PWY8E9C0WXB6, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3DGW3RFQ0GM9ERQRZDWDX, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3G4YV0CKEQHRXS2PS8NQN, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3JTD9G4MEDEDWPRBCPPRN, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3NFMSSZ5KGECQET6K46AD, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>, <ulid: 01CVN3R6Y2BVRX3FTM1NSTZ0WG, mint: 1541512800000, maxt: 1541520000000, range: 2h0m0s>"`

**Comment by twforeman** [comment] 2018-11-06 18:19
> I suspect this is something to do with the head block (not sure, will know from logs), and that the head block of the snapshot and the new head block overlap. Did you have the head in your snapshot? (`skip_head=false`).

It doesn't appear to make any difference whether I include the skip_head=false option or not. It still fails in about four hours.

**Comment by krasi-georgiev** [comment] 2018-11-06 18:44
the problem here looks different than your assumption. All these blocks that overlap have the same time range of 1541512800000-1541520000000. These time ranges are taken form the meta.json file from each directory so I don't see how it can be related to the hard linking. If it was something to hard linking only one or few should be affected, not so many.

I will try to replicate and will see what are the results.

**Comment by twforeman** [comment] 2018-11-06 19:17
Okay, well like I said it was just a thought.

**Comment by krasi-georgiev** [comment] 2018-11-06 20:04
yeah every suggestion helps :+1:

**Comment by codesome** [comment] 2018-11-07 10:12
@twforeman IIUC, to replicate this 
1. Take a snapshot
2. Wait for sometime and point prometheus to the snapshot
3. Just wait and watch for it to error out

Am I correct?

**Comment by codesome** [comment] 2018-11-07 12:46
Replicating this was very simple. In case anyone is looking to replicate this, here is what I did
1. Set block duration to `2m`.
2. Run prometheus till you have about 4-5 persisted blocks.
3. Take snapshot and shut down prometheus and wait for 5m.
4. Restart prometheus using the snapshot. 

As simple as that.

**Comment by twforeman** [comment] 2018-11-07 13:40
Just for completeness, this is what I am doing to cause the issue:

1. Run prometheus for a bit to create some data.
1. Create a snapshot
1. Copy the snapshot to AWS S3
1. Create a new data volume
1. Copy the snapshot from S3 to the new data volume
1. Stop prometheus and mount the new data volume
1. Start prometheus and wait about four hours

**Comment by krasi-georgiev** [comment] 2018-11-08 12:46
I have worked on these parts of the code recently so will look into it.

**Comment by krasi-georgiev** [comment] 2018-11-08 13:51
@twforeman I figured the problem and it is a side effect of including the head. so in your case you can do the snapshots using `/api/v1/admin/tsdb/snapshot?skip_head=true` or wait to see if https://github.com/prometheus/prometheus/pull/4653 will get merged as it addresses exactly this problem.

**Comment by twforeman** [comment] 2018-11-08 15:29
I'm testing out the 'skip_head=true' option, but using that option appears to have made it lose about 3+ hours of data (I assume that was in the head in memory).

Is there an api call to flush the head to disk before taking the snapshot? Or a setting to change it so it doesn't lose quite so much data?

**Comment by twforeman** [comment] 2018-11-08 16:39
@dbarranco I'm trying to make scripted automatic backups, so there is no way for me to watch for a compact to run and then trigger a backup...

**Closed** 2018-11-14 13:15 UTC

**Comment by twforeman** [comment] 2018-11-15 15:19
So it's 7 days later now and our prometheus server is returning a 502 Service Unavailable when we try and get data out of it. This is from the restored database.

There is nothing useful in the logs, so I'm not sure what to look at. Can we re-open this, or should I create a new task?

@krasi-georgiev

**Comment by krasi-georgiev** [comment] 2018-11-15 16:11
doesn't sound like it is related to snapshoting so I would say a new issue.

Are you sure the problem is not with some ingress path or a proxy before Prometheus?
