### ISSUE TITLE
Data race in wal sync

### ISSUE THREAD

**Issue by grobie** [prometheus/tsdb#174] opened 2017-10-10 15:27 UTC
```
2017-10-10_15:24:37.83723 ==================
2017-10-10_15:24:37.83726 WARNING: DATA RACE
2017-10-10_15:24:37.83726 Write at 0x00c4c4f0cc40 by goroutine 861:
2017-10-10_15:24:37.83727   internal/poll.(*FD).destroy()
2017-10-10_15:24:37.83727       /usr/lib/go/src/internal/poll/fd_unix.go:63 +0xa7
2017-10-10_15:24:37.83727   internal/poll.(*FD).decref()
2017-10-10_15:24:37.83727       /usr/lib/go/src/internal/poll/fd_mutex.go:211 +0x55
2017-10-10_15:24:37.83728   internal/poll.(*FD).Close()
2017-10-10_15:24:37.83728       /usr/lib/go/src/internal/poll/fd_unix.go:81 +0xf5
2017-10-10_15:24:37.83728   os.(*file).close()
2017-10-10_15:24:37.83728       /usr/lib/go/src/os/file_unix.go:201 +0x45
2017-10-10_15:24:37.83729   os.(*File).Close()
2017-10-10_15:24:37.83729       /usr/lib/go/src/os/file_unix.go:193 +0x55
2017-10-10_15:24:37.83729   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).cut.func1()
2017-10-10_15:24:37.83729       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:566 +0x141
2017-10-10_15:24:37.83730 
2017-10-10_15:24:37.83730 Previous read at 0x00c4c4f0cc40 by goroutine 20:
2017-10-10_15:24:37.83730   os.(*File).Fd()
2017-10-10_15:24:37.83731       /usr/lib/go/src/os/file_unix.go:70 +0x8e
2017-10-10_15:24:37.83732   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/fileutil.Fdatasync()
2017-10-10_15:24:37.83732       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/fileutil/sync_linux.go:33 +0x38
2017-10-10_15:24:37.83732   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).Sync()
2017-10-10_15:24:37.83732       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:623 +0xe7
2017-10-10_15:24:37.83733   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).run()
2017-10-10_15:24:37.83733       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:666 +0x188
2017-10-10_15:24:37.83733 
2017-10-10_15:24:37.83734 Goroutine 861 (running) created at:
2017-10-10_15:24:37.83734   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).cut()
2017-10-10_15:24:37.83734       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:555 +0x80a
2017-10-10_15:24:37.83734   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).write()
2017-10-10_15:24:37.83736       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:712 +0xa6
2017-10-10_15:24:37.83736   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*SegmentWAL).LogSamples()
2017-10-10_15:24:37.83737       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:454 +0x143
2017-10-10_15:24:37.83737   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*headAppender).Commit()
2017-10-10_15:24:37.83737       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/head.go:486 +0x194
2017-10-10_15:24:37.83737   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.dbAppender.Commit()
2017-10-10_15:24:37.83738       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:306 +0x42
2017-10-10_15:24:37.83738   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*dbAppender).Commit()
2017-10-10_15:24:37.83738       <autogenerated>:1 +0x7a
2017-10-10_15:24:37.83738   github.com/prometheus/prometheus/storage/tsdb.appender.Commit()
2017-10-10_15:24:37.83739       /home/grobie/code/go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:224 +0x3e
2017-10-10_15:24:37.83739   github.com/prometheus/prometheus/storage/tsdb.(*appender).Commit()
2017-10-10_15:24:37.83740       <autogenerated>:1 +0x71
2017-10-10_15:24:37.83740   github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit()
2017-10-10_15:24:37.83740       /home/grobie/code/go/src/github.com/prometheus/prometheus/storage/fanout.go:140 +0x6e
2017-10-10_15:24:37.83740   github.com/prometheus/prometheus/retrieval.(*timeLimitAppender).Commit()
2017-10-10_15:24:37.83741       <autogenerated>:1 +0x5b
2017-10-10_15:24:37.83741   github.com/prometheus/prometheus/retrieval.(*scrapeLoop).append()
2017-10-10_15:24:37.83741       /home/grobie/code/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:928 +0x114e
2017-10-10_15:24:37.83741   github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run()
2017-10-10_15:24:37.83742       /home/grobie/code/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:672 +0xaa4
2017-10-10_15:24:37.83742 
2017-10-10_15:24:37.83742 Goroutine 20 (running) created at:
2017-10-10_15:24:37.83742   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.OpenSegmentWAL()
2017-10-10_15:24:37.83743       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/wal.go:227 +0x709
2017-10-10_15:24:37.83743   github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open()
2017-10-10_15:24:37.83743       /home/grobie/code/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:207 +0x667
2017-10-10_15:24:37.83744   github.com/prometheus/prometheus/storage/tsdb.Open()
2017-10-10_15:24:37.83744       /home/grobie/code/go/src/github.com/prometheus/prometheus/storage/tsdb/tsdb.go:130 +0x3ab
2017-10-10_15:24:37.83744   main.main.func3()
2017-10-10_15:24:37.83744       /home/grobie/code/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:317 +0x2cf
2017-10-10_15:24:37.83745 ==================
```

**Comment by dim** [comment] 2017-10-13 13:27
Confirmed:

```
==================
WARNING: DATA RACE
Write at 0x00c420140600 by goroutine 47:
  internal/poll.(*FD).destroy()
      ~/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_unix.go:63 +0xa7
  internal/poll.(*FD).decref()
      ~/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_mutex.go:211 +0x55
  internal/poll.(*FD).Close()
      ~/.gimme/versions/go1.9.linux.amd64/src/internal/poll/fd_unix.go:81 +0xf5
  os.(*file).close()
      ~/.gimme/versions/go1.9.linux.amd64/src/os/file_unix.go:201 +0x45
  os.(*File).Close()
      ~/.gimme/versions/go1.9.linux.amd64/src/os/file_unix.go:193 +0x55
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).cut.func1()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:573 +0x141

Previous read at 0x00c420140600 by goroutine 36:
  os.(*File).Fd()
      ~/.gimme/versions/go1.9.linux.amd64/src/os/file_unix.go:70 +0x8e
  mypkg/vendor/github.com/prometheus/tsdb/fileutil.Fdatasync()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/fileutil/sync_linux.go:33 +0x38
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).Sync()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:630 +0xe7
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).run()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:673 +0x188

Goroutine 47 (running) created at:
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).cut()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:562 +0x80a
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).write()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:719 +0xa6
  mypkg/vendor/github.com/prometheus/tsdb.(*SegmentWAL).LogSeries()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:434 +0x143
  mypkg/vendor/github.com/prometheus/tsdb.(*headAppender).Commit()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/head.go:514 +0xfd
  mypkg/vendor/github.com/prometheus/tsdb.(*initAppender).Commit()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/head.go:415 +0x6e
  mypkg/vendor/github.com/prometheus/tsdb.dbAppender.Commit()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/db.go:306 +0x42
  mypkg/vendor/github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a

Goroutine 36 (running) created at:
  mypkg/vendor/github.com/prometheus/tsdb.OpenSegmentWAL()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/wal.go:233 +0x709
  mypkg/vendor/github.com/prometheus/tsdb.Open()
      ~/go/src/mypkg/vendor/github.com/prometheus/tsdb/db.go:207 +0x667
==================
```

**Comment by beorn7** [comment] 2017-10-25 15:11
Still seeing this (unsurprisingly, I guess, as no fix has been attempted, if I'm informed correctly).

Wouldn't this be a release blocker? I'm not an expert of the Go execution model but isn't the basic rule that all bets are off once you have run into a data race? @fabxc ?

**Comment by fabxc** [comment] 2017-10-25 15:15
Yea, I noted it down elsewhere that it's basically attempting an fsync on a closed file descriptor. Which is 'fine' let's say because it was properly fsync'd before closing.

Kinda having the assumption here that undefined behavior in case of a race is somehow bound on the address space it's affecting, i.e. it doesn't run `rm -rf /` just because you tried to fsync a closed file.  
I suppose in strict terms undefined truly means that though. If there's a strong concern around this, I can work on getting rid of it.
FWIW, err'ing on the safe side shortly before the release, I'd just revert the changes @alin-amana made to make the WAL less blocking, which removes the race. Not sure whether that's worth it.

**Comment by beorn7** [comment] 2017-10-26 13:52
Disclaimer: I am certainly not the one to make the call about the release.

Just saying, in very general, that any weirdness we might encounter, especially "Heisenbugs", will make us think about "there is a data race, so that might explain _anything_". Since those weird things are difficult to reproduce, I would feel much better if we could rule out known races from the beginning.

**Comment by fabxc** [comment] 2017-10-26 14:46
Understood and certainly fair point. I'll look what's the most viable
option given our timeline.
I've a super dope POC of a nonblocking/lock-free WAL as well. But that's
totally out of scope unfortunately.

**Comment by beorn7** [comment] 2017-11-27 12:16
This one can be closed, can it not?

**Comment by krasi-georgiev** [comment] 2018-08-31 10:54
with so many code changes since than, lets close and will revisit if we get a new report.

**Closed by krasi-georgiev** 2018-08-31 10:54 UTC
