### ISSUE TITLE
WAL log samples: log series: write metrics/wal/000315: file already closed

### ISSUE THREAD

**Issue by iksaif** [prometheus/tsdb#317] opened 2018-04-16 11:42 UTC
This is something that happens when the disk is full. The caller should probably have a proper health check for that, but it's another story(https://github.com/prometheus/prometheus/issues/3283). tsdb should certainly not try to write to an already closed file.

This must come from:
https://github.com/prometheus/tsdb/blob/b7173eb0e5558c720ec4c939af7e803d38aa1cce/wal.go#L763 and the fact that in https://github.com/prometheus/tsdb/blob/b7173eb0e5558c720ec4c939af7e803d38aa1cce/wal.go#L604 the function returns early without setting `cur` to `nil` on failure.

I suspect that we should instead set `cur` to `nil` early in `cut()` and handle this case in `write()`.

cc: @Thib17

**Comment by krasi-georgiev** [comment] 2018-04-17 07:57
Thanks for the nice pointers. I will check this bug.

**Comment by krasi-georgiev** [comment] 2018-04-17 09:25
I can't seem to replicate it.

```
fallocate -l 50M disk.img
mkfs disk.img
sudo mount -o loop disk.img ./data
sudo chmod -R 777 data
go run main.go  uname_default.go fdlimits_default.go --config.file=../../promBench.yml
```

<details><summary>prom config</summary>

```
global:
  scrape_interval:     200ms # Set the scrape interval to every 15 seconds. Default is every 1 minute.
 
scrape_configs:
  - job_name: 'master'
    # scrape_interval: 50ms 
    static_configs:
      - targets: ['localhost:9090']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus1'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus3'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus4'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus5'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus6'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus7'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus8'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus9'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus10'
    static_configs:
      - targets: ['localhost:9090']
  ```

</details>

```
level=warn ts=2018-04-17T09:14:42.7401957Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus7 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
level=warn ts=2018-04-17T09:14:42.74177436Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus22 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
level=warn ts=2018-04-17T09:14:42.75743852Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus1 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
```

```
cp -R data dataB
sudo umount ./data
cp -R dataB data
```

at this point prometheus starts and works as expected on the disk that has enough disk space.

**Comment by iksaif** [comment] 2018-04-17 10:03
Sorry, I missed an important part here: the issue is that once you've had ` no space left on device` once, it will become `file already closed` the next time, which is confusing for the administrator.

If you set `cur` to `nil` just after closing the file, the error will keep making sense.

**Comment by krasi-georgiev** [comment] 2018-04-17 10:16
I must be doing something different as my logs never show `file already closed`

**Comment by krasi-georgiev** [comment] 2018-04-17 10:33
yep , got it and replicated. will test your suggestion and will open the PR.

**Comment by amitsingla** [comment] 2018-08-21 17:49
@iksaif @krasi-georgiev I start facing this issue on one of the production cluster . Do we find any solution or Work around for the same. I checked the  prlimit and looks good..

Prometheus version: 2.3.0
prlimit values

```
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
AS         address space limit                unlimited unlimited bytes
CORE       max core file size                 unlimited unlimited blocks
CPU        CPU time                           unlimited unlimited seconds
DATA       max data size                      unlimited unlimited bytes
FSIZE      max file size                      unlimited unlimited blocks
LOCKS      max number of file locks held      unlimited unlimited
MEMLOCK    max locked-in-memory address space     65536     65536 bytes
MSGQUEUE   max bytes in POSIX mqueues            819200    819200 bytes
NICE       max nice prio allowed to raise             0         0
NOFILE     max number of open files             1048576   1048576
NPROC      max number of processes               514236    514236
RSS        max resident set size              unlimited unlimited pages
RTPRIO     max real-time priority                     0         0
RTTIME     timeout for real-time tasks        unlimited unlimited microsecs
SIGPENDING max number of pending signals         514236    514236
STACK      max stack size                       8388608 unlimited bytes
```

**Comment by krasi-georgiev** [comment] 2018-08-21 23:41
IIRC this wasn't a bug, but mainly misleading logs.
The next release includes quite a few changes for these parts of the code base so best to wait and if it behaves the same I can revisit.

**Comment by szediktam** [comment] 2018-10-16 02:50
I have a similar issue in my cluster.   there are many tmp files in /var/lib/prometheus/data, like 01CSVYYZ2N77NT2VEQ47P93FB5.tmp, about 500M.They ate up my disk space for /var/lib/prometheus/data.  And the log show as following:
 | level=warn ts=2018-10-14T15:59:58.720480291Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:58.914424272Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.107081533Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.257552091Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=error ts=2018-10-14T15:59:59.559349479Z caller=wal.go:713 component=tsdb msg="sync failed" err="flush buffer: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.608324272Z caller=scrape.go:673 component="target manager" scrape_pool=kubernetes-service-endpoints target=http://10.233.65.190:9095/metrics msg="append failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.609563487Z caller=scrape.go:677 component="target manager" scrape_pool=kubernetes-service-endpoints target=http://10.233.65.190:9095/metrics msg="append failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.824557393Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.82479578Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.824943819Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.825075107Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.825201263Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.825357478Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.833987628Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.83425203Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.834421827Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.834695948Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.851145342Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"
 | level=warn ts=2018-10-14T15:59:59.867473227Z caller=manager.go:371 component="rule manager" group=kubernetes.rules msg="rule sample appending failed" err="WAL log samples: log series: write /var/lib/prometheus/data/wal/000541: file already closed"



Any solution for this? Thank you.
@iksaif  @krasi-georgiev

**Comment by simonpasquier** [comment] 2018-10-16 08:14
@szediktam if you had a disk full event then you can remove all .tmp files to recover space. Also you might want to upgrade to the latest Prometheus release, rather than using v2.0.0.

**Comment by krasi-georgiev** [comment] 2018-10-16 09:04
@szediktam yeah the tmp files was a bug which is not fixed so an upgrade will solve it.

**Comment by szediktam** [comment] 2018-10-16 11:56
if I remove the .tmp files, it will generate many .tmp files again to eat up my disk space. @simonpasquier 

@krasi-georgiev The newer version fix this bug? which patch on which version?

**Comment by simonpasquier** [comment] 2018-10-16 12:20
@szediktam it will hard to pin point which commit fixed the issue but if you upgrade to v2.4.3 and remove the .tmp files, you should be good.

**Comment by szediktam** [comment] 2018-10-17 02:17
Ok. Thanks.

How to reproduce this? I should reproduce this, and upgrade to v2.4.3 to solve this, to prove that it works.

**Comment by wryfi** [comment] 2018-11-15 03:39
In my case, this happened because the ulimit for open files was set too low.  I had to edit my init configuration to increase the ulimit, and prometheus was happy again.

The somewhat insidious behavior is that the "too many open files" message was only written at the very top of the log, while the rest of it was full of "file already closed" messages, which don't really describe the root cause of the problem.  I didn't actually notice the open files problem until I happened to tail the log while restarting the process.

It would be great if the root cause of the error were logged throughout.

**Comment by hello4nithya** [comment] 2019-05-07 12:45
> In my case, this happened because the ulimit for open files was set too low. I had to edit my init configuration to increase the ulimit, and prometheus was happy again.
> 
> The somewhat insidious behavior is that the "too many open files" message was only written at the very top of the log, while the rest of it was full of "file already closed" messages, which don't really describe the root cause of the problem. I didn't actually notice the open files problem until I happened to tail the log while restarting the process.
> 
> It would be great if the root cause of the error were logged throughout.

How did you set the ulimit in prometheus container

**Comment by krasi-georgiev** [comment] 2019-06-05 09:27
this is fixed in https://github.com/prometheus/tsdb/pull/582
tsdb continues to write when there is more space available.

**Closed by krasi-georgiev** 2019-06-05 09:27 UTC
Labels: enhancement / cleanup, priority: medium
