### ISSUE TITLE
Unknown series references in WAL after crash

### ISSUE THREAD

**Issue by fabxc** [prometheus/tsdb#21] opened 2017-03-24 12:34 UTC
After ungraceful termination sometimes samples in the WAL reference series that do not exist yet. This should strictly not happen as all newly created series are added (in-order) to the WAL before any of their samples.

Needs investigation but no critical impact at this stage.

**Comment by devnev** [comment] 2017-06-12 09:50
We're running a prometheus2 instance alongside our prometheus instances to observe the system's behaviour as we'd like to switch to P2 as soon as its ready. This crash seems insofar impacting as it can get a prometheus2 completely stuck in a crashloop: Our instance logs `Opening storage failed: open block /prometheus-data/01BJ772AN91568QNCGANK95GM7: open head block /prometheus-data/01BJ772AN91568QNCGANK95GM7: unknown series reference 101615 (max 101608); abort WAL restore" source="main.go:89"` on startup and terminates, to then be restarted by k8s and repeat.

**Comment by mwitkow** [comment] 2017-06-12 10:05
https://github.com/prometheus/prometheus/issues/2795 is the same thing :(

**Comment by fabxc** [comment] 2017-07-05 13:02
Did either of you ever observe this again?

**Comment by WuLeeX** [comment] 2018-01-20 08:30
Any updates on this？

**Comment by roidelapluie** [comment] 2018-07-19 12:00
I observe that behaviour too after arn early restart of prometheus

**Comment by roidelapluie** [comment] 2018-07-19 12:01
Jul 19 13:59:50 nip-prometheus1 prometheus[27159]: level=warn ts=2018-07-19T11:59:50.793064439Z caller=head.go:320 component=tsdb msg="unknown series references in WAL samples" count=84

**Comment by roidelapluie** [comment] 2018-07-19 12:02
I have an impact as some recording rules do not have the correct timestamp it seems. Like they are delayed by a few minutes.

**Comment by krasi-georgiev** [comment] 2018-07-23 16:03
Initially I thought that this is caused by more than one prometheus writing to the same data folder, but @brian-brazil found some parts of the code that are more likely to cause this.
https://github.com/prometheus/tsdb/pull/332#discussion_r195148633

It is best to get the WAL rewrite merged and than work on this bug after.

**Comment by JorritSalverda** [comment] 2019-01-16 19:41
Seeing this in 2.6.0 as well, after having upgraded from 2.3.2 a couple of days ago.

```
level=info ts=2019-01-16T19:14:28.556334137Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1546545600000 maxt=1546552800000 ulid=01D18NC97NQE2TMPDRPS77T1KJ
level=info ts=2019-01-16T19:14:28.559075926Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1546552800000 maxt=1546560000000 ulid=01D18Q3MRBYZMKBKFGQQP7G6ZW
level=info ts=2019-01-16T19:14:28.565815055Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1546560000000 maxt=1546567200000 ulid=01D18RREY7F5CPXFVNY60BMCXE
level=info ts=2019-01-16T19:14:28.567392945Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1546567200000 maxt=1546574400000 ulid=01D18VZ6Y0QKW3AVHCRS5EQ58P
level=warn ts=2019-01-16T19:30:20.419156581Z caller=head.go:434 component=tsdb msg="unknown series references" count=462961
```

**Closed** 2019-04-09 13:16 UTC
Labels: bug, priority: medium
