### ISSUE TITLE
Panic when reading chunk

### ISSUE THREAD

**Issue by tnachen** [prometheus/tsdb#251] opened 2018-01-11 00:31 UTC
panic: runtime error: index out of range
```
goroutine 1 [running]:
github.com/prometheus/tsdb/chunks.(*Reader).Chunk(0xc420010d00, 0x901e7a2bb, 0xc427e14460, 0xc427e096b0, 0x411b47, 0xc42027e340)
        /home/tim/go/src/github.com/prometheus/tsdb/chunks/chunks.go:366 +0x50f
github.com/prometheus/tsdb.(*blockChunkReader).Chunk(0xc427e14380, 0x901e7a2bb, 0x1e, 0x20, 0xc420088140, 0x2)
        <autogenerated>:1 +0x46
github.com/prometheus/tsdb.(*populatedChunkSeries).Next(0xc427da2240, 0x30)
        /home/tim/go/src/github.com/prometheus/tsdb/querier.go:588 +0x13f
github.com/prometheus/tsdb.(*blockSeriesSet).Next(0xc42027e300, 0xc42027e380)
        /home/tim/go/src/github.com/prometheus/tsdb/querier.go:628 +0x48
github.com/prometheus/tsdb.newMergedSeriesSet(0x928780, 0xc42027e300, 0x928780, 0xc42027e340, 0xc4299c87b0)
        /home/tim/go/src/github.com/prometheus/tsdb/querier.go:407 +0x8f
github.com/prometheus/tsdb.(*querier).sel(0xc427e14340, 0xc427e14320, 0x2, 0x2, 0xc4299c87b0, 0x1, 0x1, 0x0, 0xc42007f8c0, 0x958b30, ...)
        /home/tim/go/src/github.com/prometheus/tsdb/querier.go:108 +0x1d0
github.com/prometheus/tsdb.(*querier).Select(0xc427e14340, 0xc4299c87b0, 0x1, 0x1, 0x1, 0xc4299c87b0, 0x0, 0x1)
        /home/tim/go/src/github.com/prometheus/tsdb/querier.go:87 +0x6a
```
-----------

From printing I see that variable l is 0, which comes from:
l, n := binary.Uvarint(r) // l is zero

**Comment by Gouthamve** [comment] 2018-01-11 02:25
Hi, can you share how you hit this error? Anyway we could reproduce it on our end?

**Comment by tnachen** [comment] 2018-01-11 04:39
I was just running on a Select with a label equal matcher on a prometheus snapshot dataset.
One of the directory gave me this error, I have the directory but I'm not sure what's the easiest way to find out which part causes this problem. Any suggestions?

**Comment by Gouthamve** [comment] 2018-01-11 08:50
Can you share the code you ran? Also if possible upload the directory if possible?

**Comment by tnachen** [comment] 2018-01-11 08:54
It's a simple query:

q, err := db.Querier(math.MinInt64, math.MaxInt64)
        if err != nil {
                return nil, fmt.Errorf("Unable to create queries: " + err.Error())
        }
matcher := labels.NewMatchEqualer("__name__", "abc")
 set, err := q.Select(matcher)
        if err != nil {
                return nil, fmt.Errorf("Unable to select: " + err.Error())
        }

Sorry I can't upload the data as it's not sharable. But if you tell me any suggestion to look into something I can do so.

**Comment by Gouthamve** [comment] 2018-01-12 05:10
Hi, this is weird and points to a corruption afaics. The chunk length is not decodable :/

**Comment by tnachen** [comment] 2018-01-12 05:45
I see, let me figure out where the chunk length bytes are and I can post
that. AFAIK it’s a successfully snapshot from Prometheus, and just one of
the folders has this problem.

**Comment by Gouthamve** [comment] 2018-01-28 16:19
@tnachen, any updates on this?

**Comment by krasi-georgiev** [comment] 2018-08-31 12:11
closing due to the age.

@tnachen feel free to reopen if there is an update and we can figure out how to replicate.

**Closed by krasi-georgiev** 2018-08-31 12:11 UTC
