### ISSUE TITLE
Read-path in TSDB doesn't honor context

### ISSUE THREAD

**Issue by jacksontj** [prometheus/tsdb#411] opened 2018-10-15 22:30 UTC
I ran into a situation in prometheus where a user was sending a very large query and it was running past the timeout. While investigating this issue I found that tsdb doesn't honor the context for reads (e.g. https://github.com/prometheus/tsdb/blob/master/querier.go#L155). What this means is if a client sends a query for a large set of series then the caller (prometheus) has to wait for tsdb to complete before timing out the request. From the quick looking I did this should actually be a fairly simple addition, as the various lookup methods would need to take a context and check it. This doesn't seem like a huge amount of effort, and I'd definitely be willing to submit the PR. So, would you guys be interested in something like this if I where to submit a PR for it?

**Comment by krasi-georgiev** [comment] 2018-10-15 23:16
this looks like a dupe of https://github.com/prometheus/tsdb/issues/84

I haven't looked into it, but IIRC it wasn't trivial to implement hence the issue being opened for so long.

**Comment by jacksontj** [comment] 2018-10-15 23:28
#84 encompasses both the read and write path. As #84 states this is complex on the write path, but this issue is focused solely on the read path, as it seems that the read side should be doable (significantly less complex).

**Comment by krasi-georgiev** [comment] 2018-10-16 00:11
I just had a quick look over the past discussions and tend to agree with fabian's comment in https://github.com/prometheus/prometheus/issues/3480#issuecomment-345152830 that passing a context in such hot paths won't really help a lot. 

I haven't done a proper research on the topic so if you want to invest the time than please open a PR against Prometheus, ping me and I will start a benchmark so we can test if it would behave better than what we have now.

**Comment by jacksontj** [comment] 2018-10-16 17:49
After doing some more digging, it seems that the vast majority of the time is actually spent in [`SortedPostings`](https://github.com/prometheus/tsdb/blob/master/head.go#L1035). I'm not sure why that sort is necessary, but if it is in fact required then some sort of cancellation there seems like it would do the trick.

**Comment by krasi-georgiev** [comment] 2018-10-16 19:09
nice! thanks for spending the time for this. btw what did you use to visualise the bench results?

@gouthamve , @fabxc do you see any problem in adding a context for `SortedPostings` so this can be cancelled?

**Comment by jacksontj** [comment] 2018-10-16 20:05
@krasi-georgiev I used google sheets, So nothing fancy :)

**Comment by jacksontj** [comment] 2018-10-16 20:09
@krasi-georgiev One other question, do you know why that sort is required to begin with?

**Comment by jacksontj** [comment] 2018-10-16 22:36
So I've been digging into this a bit more, and I believe I understand the issue better. The SortedPostings is only expensive in the `head` block because things aren't sorted already (same case in the test implementation). All blocks that have moved from head to an immutable block are sorted when they are persisted. What this means is right now all queries that hit the head block are significantly slower at this portion because they are *each* sorting the series' labels as they query. Unless we want to change that HEAD block to maintain sort order on insert/addition (which could be done per-shard, and merged using a heap) we'll be stuck with how it is.

**Comment by fabxc** [comment] 2018-10-17 08:48
Thanks for the analysis. Indeed `SortedPostings` is an outlier here with its big blocking computation.
Though the only way for passing a context to work would be to re-implement sorting since `sort.Sort`, where the time is actually spent, does not take a context either.
Unless your benchmark showed that the expansion of the postings list beforehand actually consumes a majority of the time.

Giving `SortedPostings` a context argument isn't enough of course, since it's called by other public methods. So this would be a further reaching change.

@jacksontj early on I actually tried to maintain a sorting of the IDs. It turned out to have significant problems since at startup or when a lot of targets appear, a massive bunch of series is inserted and must be added to the sort mapping. Approaches that could deal well with that usually had a high baseline cost, which didn't go well with the fact that in large setups single new series are appearing pretty much every few seconds.
That was a long time ago though and it would be great for someone to give this another shot.

I eventually went back to just resorting for each query since the assumption was that a few 10k series are the maximum for any realistic queries and for that performance seemed perfectly alright.

**Comment by jacksontj** [comment] 2018-10-17 16:36
> Though the only way for passing a context to work would be to re-implement sorting since sort.Sort, where the time is actually spent, does not take a context either.

We actually don't need much of an implementation to get cancellation, simply wrapping the sort method and using `recover()` [does the trick](https://github.com/jacksontj/tsdb/blob/issue_411_context/util.go#L8).

> Unless your benchmark showed that the expansion of the postings list beforehand actually consumes a majority of the time.

I re-ran the benchmark while adding some prints to track time of the various pieces, here is the data from a run with 1000 series:
```
postingsForMatcher all 4.8µs
SortedPostings - postings iterator 9.701035ms
SortedPostings - sort 3.776977868s
SortedPostings - NewListPostings 886ns
ix.SortedPostings 3.786722714s
total time 3.786758744s
```

In that we can see that almost all of the time is in the sort, so thats the main place to tackle

> Giving SortedPostings a context argument isn't enough of course, since it's called by other public methods. So this would be a further reaching change.

I noticed while implementing the benchmarks etc. I actually have a branch with this mostly completed, so to speed up discussions a bit I've opened PR #416 with my code.

>  That was a long time ago though and it would be great for someone to give this another shot.

I'm curious to give this a shot, but my guess is that its going to be a significantly larger change, so we should probably finish this one separately first :)


So the PR I have adds context into the sort path and adds tests that cancellation happens within 1ms of the context cancellation time (seems more than sufficient of an error bar). If we're okay with the approach I can do a pass cleaning it up before we get it merged, otherwise we can iterate from there.

**Comment by jacksontj** [comment] 2018-10-17 17:11
Another piece of information, I added a benchmark using the blocks to compare head to block performance:

```
BenchmarkBlockQuerier/1000000/100ms/head/equal_all-4         	       1	4649141196 ns/op
BenchmarkBlockQuerier/1000000/100ms/block/equal_all-4        	    5000	    242018 ns/op
```
From this we can see that head performance is significantly worse (4.6s vs 0.24ms). So after getting this timeout stuff in, definitely seems worth looking into maintaining sort somehow.

**Comment by jacksontj** [comment] 2018-10-22 16:33
@fabxc I assume that this cancellation idea in the PR is acceptable? If so I can clean up that PR and we can get it merged in. I did spend some time looking into maintaining sort on the HEAD block, but that'll require more time as the few simple attempts where much slower (as I imagine you also experienced).

**Comment by krasi-georgiev** [comment] 2018-10-22 17:35
if you don't mind lets not rush it.
This would require changing many public interfaces so I want do some thinking before we commit to the context idea.

I need to clear some other pending PRs and will put some more time into this.

**Comment by jacksontj** [comment] 2018-10-22 18:00
Sure, my intention isn't to rush so much as to make sure this is the
approach we want-- since there was no update on the progress for a week.
It's also unclear what the compatibility guarantees are ok various
interfaces (as this changes some exposed public methods, but not the
querier etc.).

So at this point I'm just looking for feedback to make sure the pr is what
we are looking for. But if it needs to wait for a couple others that's
definitely fine, thanks for the update :)

**Comment by krasi-georgiev** [comment] 2018-11-06 18:38
I don't think I can have a look at this anytime soon as there are few more urgent pending bugs.

**Comment by jacksontj** [comment] 2018-11-30 20:16
Bump to check on this :)

**Comment by krasi-georgiev** [comment] 2018-12-10 11:44
I am starting to look into this now.


If `SortedPostings` in the `Head` is the culprit here why not try to solve the problem there and avoid having  context all together?

**Comment by jacksontj** [comment] 2018-12-17 19:35
friendly bump :)

**Comment by krasi-georgiev** [comment] 2018-12-18 11:13
haven't forgotten, just again need to complete few other older PRs and reviews.

**Comment by krasi-georgiev** [comment] 2018-12-28 12:08
@jacksontj 	I started looking into this again and Fabian's comment suggests that it is hard, but I prefer that we spend some time to look into fixing the underlying problem before polluting all interfaces with a context.

I am studying the code for postings and will post if I have any ideas. If you have time I would appreciate if you can look into that as well and suggest some ideas as well.

**Comment by krasi-georgiev** [comment] 2018-12-28 17:16
after some discussions with @brian-brazil (which led to some optimisation of the sorting in https://github.com/prometheus/tsdb/pull/485) it seems not worth it yet to pollute the interfaces with a context. Even with 10m series the sorting would finish in a reasonable time (in your bench results it is 3s which is not that much).
 
If you are  experiencing some real performance issues can you please include some details and we will try to address these and try to do it without adding a  context.

**Comment by jacksontj** [comment] 2019-01-02 18:41
@krasi-georgiev I'm glad that an optimization was easily possible there. The performance issue still exists from my experience though. Although we see a 3s runtime in benchmarks, in a real production system I end up seeing significantly longer times (5m+ regularly for ~10M series) -- presumably due to memory allocation delays finding contiguous memory on a live system. As such in practice this seems to still be a necessary addition.

**Comment by brian-brazil** [comment] 2019-01-02 19:02
Try it with #485, which aside from being faster in raw terms should also greatly reduce contention that would should up in production.

**Comment by jacksontj** [comment] 2019-01-04 23:00
I ran 2.6 with the patch from #485 and it went from 514s -> 120s (seemingly timing out correctly). So from what I see its still not cancelling when the context is, but the perf seems more inline with the benchmarks so that few second delay is tolerable. With this I'll go ahead and close out my PR -- we can add it back in later if there is interest in canceling at the "right" time, but #485 seems to resolve my major pain point.

**Comment by brian-brazil** [comment] 2019-01-05 00:08
Great! If we need better cancellation in future due to something else taking a bit too much time, we can always add contexts.

**Comment by krasi-georgiev** [comment] 2019-01-05 03:36
@jacksontj 	thanks for the update. 
Can we close this issue than?

**Closed** 2019-01-05 06:39 UTC
